SE 3358 - Better selection of work-owner
DBCDK/work-presentation pull request #58
Opened 2021-02-08 07:30 UTC by mb-dbc-dk

Select dc fields from each manifestation into `priorityKeys`
Select the most relevant (from age / type / edition / owner), and use it as work-owner.

2021-02-08 08:08 UTC, kwcdbc requested changes
Jeg kunne godt bruge at der var en unit test for funktionen computeValues med et lidt mere rigtigt eksempel på hvordan input data ser ud (manifestations).

2021-02-08 08:08 UTC, kwcdbc commented on javascript/src/main/resources/javascript/SelectOwnerPriority.use.js
> +     * @param {Object} manifestations as a map from id tp java-type ManifestationInformation
from id tp java-type - tp?

2021-02-08 08:08 UTC, kwcdbc commented on javascript/src/main/resources/javascript/SelectOwnerPriority.use.js
> +     * @return {Object} map of maniferstationid to relevance as owner
maniferstationid  --> manifestation id

2021-02-08 08:08 UTC, kwcdbc commented on javascript/src/main/resources/javascript/SelectOwnerPriority.use.js
> +     * Function that finds the key with the higest value in a map
higest --> highest

2021-02-08 08:08 UTC, kwcdbc commented on javascript/src/main/resources/javascript/SelectOwnerPriority.use.js
> +     * @param {Object} map of maniferstationid to relevance as owner
Der er vist et par steder den her er blevet kopieret rundt
maniferstationid --> manifestation id

2021-02-08 08:08 UTC, kwcdbc commented on javascript/src/main/resources/javascript/SelectOwnerPriority.use.js
> +     * Function that multitplies the 2nd maps values to the 1st
multitplies  --> multiplies

2021-02-08 08:08 UTC, kwcdbc commented on javascript/src/main/resources/javascript/SelectOwnerPriority.use.js
> +     * Function that creates a baseline of relevanve for each manifestation in the map
relevanve --> relevance

2021-02-08 08:08 UTC, kwcdbc commented on javascript/src/main/resources/javascript/SelectOwnerPriority.use.js
> +     * @param {Object} manifestations as a map from id tp java-type ManifestationInformation
tp?

2021-02-08 08:08 UTC, kwcdbc commented on javascript/src/main/resources/javascript/SelectOwnerPriority.use.js
> +     * Function that that finds a priority of a type
that that

2021-02-08 08:08 UTC, kwcdbc commented on javascript/src/main/resources/javascript/SelectOwnerPriority.use.js
> +     * The list TYPE_PRIORITY is ised to determine the priority of a manifestation.
ised --> used

2021-02-08 08:08 UTC, kwcdbc commented on javascript/src/main/resources/javascript/SelectOwnerPriority.use.js
> +        for ( ; ; ) {
sådan en for løkke har jeg aldrig set før, kan du forklare den?

2021-02-08 08:08 UTC, kwcdbc commented on javascript/src/main/resources/javascript/SelectOwnerPriority.use.js
> +     * Function that that computes a relevance based upon the types tag in the ManifestationInformation
that that

2021-02-08 08:08 UTC, kwcdbc commented on javascript/src/main/resources/javascript/SelectOwnerPriority.use.js
> +     * The list TYPE_PRIORITY is ised to determine the priority of a manifestation.
ised --> used

2021-02-08 09:43 UTC, kwcdbc commented on javascript/src/main/resources/javascript/SelectOwnerPriority.test.js
> +        'b', // significantly younger
øh, er 'b' ikke ældre? den er fra 2016?

2021-02-08 09:43 UTC, kwcdbc commented on javascript/src/main/resources/javascript/SelectOwnerPriority.use.js
> +            } else if ( ( match = version.match( /^(\d+)\.? bogklubudgave/ ) ) ) {
ville det ikke ramme bedre hvis man kun forsøgte at matche på 'bogklub' i stedet for 'bogklubudgave' ?

2021-02-08 10:30 UTC, noah-dbc approved these changes

2021-02-08 10:30 UTC, noah-dbc commented on javascript/src/main/java/dk/dbc/search/work/presentation/javascript/JavascriptBuilder.java
> +    private static <T> T setOnce(String field, T oldValue, T newValue) {
Jeg synes det her navn er lidt misvisende. Der er ikke noget der bliver sat.

2021-02-08 10:38 UTC, mb-dbc-dk commented on javascript/src/main/resources/javascript/SelectOwnerPriority.test.js
> +        'b', // significantly younger
Doh..

2021-02-08 10:50 UTC, kwcdbc approved these changes

2021-02-10 06:34 UTC, mb-dbc-dk commented on javascript/src/main/java/dk/dbc/search/work/presentation/javascript/JavascriptBuilder.java
> +    private static <T> T setOnce(String field, T oldValue, T newValue) {
Kan du komme med et bedre navn?

2021-02-10 08:19 UTC, noah-dbc approved these changes

2021-02-10 08:19 UTC, noah-dbc commented on javascript/src/main/java/dk/dbc/search/work/presentation/javascript/JavascriptBuilder.java
> +    private static <T> T setOnce(String field, T oldValue, T newValue) {
njaah.. `checkAndPick` måske?

2021-02-10 08:38 UTC, merged